<table border="0">
          <tbody>
          <tr height="38">
            <td width="70" class="tit">{dede:field name='typename'/}</td>
              {dede:channel type='son' noself='yes'} 
            <td width="65"><a href="[field:typelink/]">[field:typename/]</a></td>
             {/dede:channel} 
            <td>
              
            </td>
          </tr>
        </tbody>
        </table>