
<field:sgmc itemname="水果名称" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:sgmc>

<field:sggg itemname="水果规格" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:sggg>

<field:sgcd itemname="水果产地" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:sgcd>

<field:sgkg itemname="水果口感" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:sgkg>

<field:bzqx itemname="保质期限" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:bzqx>

<field:ccff itemname="储存方法" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:ccff>

<field:sgsm itemname="水果说明" autofield="1" notsend="0" type="multitext" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:sgsm>

<field:xqpic itemname="产品详情页图片" autofield="1" notsend="0" type="img" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:xqpic>

<field:xbtp itemname="详情页下部图片" autofield="1" notsend="0" type="img" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:xbtp>
