<li><a href="fruitinfo.html">
              <div class="pic th_pic" > <img src="[field:picname/]" alt="" width="176" height="176" /></div>
              <div class="text">
            
                <div class="tit1">[field:sgmc/]</div>
                <div class="tit2">[field:sgcd/]</div>
                <div class="tag">高品质 3年挂果</div>
                <p>零售价</p>
                <div class="money">￥<span>39.00</span></div>
              </div><!--text end-->
              <div class="clear"></div> 
            </a></li>