<?php
$z[0]=Array("channel","\n        <li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\n      ",87,228);
$z[0][4]['type']="top";
$z[0][4]['typeid']="1, 2, 7";
$z[0][4]['row']="3";
$z[1]=Array("global","",282,314);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("channelartlist","\n        <li><a href=\"{dede:field name='typeurl'/}\">{dede:field name='typename'/}</a></li>\n      ",363,533);
$z[2][4]['typeid']="10, 16, 23";
$z[2][4]['row']="3";
$z[3]=Array("global","",706,738);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("global","",1429,1461);
$z[4][4]['name']="cfg_templets_skin";

?>