<?php
$z[0]=Array("global","",452,484);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("channelartlist"," \n      <li><a href=\"{dede:field name='typeurl'/}\">{dede:field name='typename'/}</a>\n          <ul class=\"bnav{dede:field name='id'/}\">\n          {dede:channel type='son' noself='yes'} \n            <li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\n          {/dede:channel} \n          </ul>\n          <div class=\"bg_nav\"></div>\n        </li>\n\n  ",726,1144);
$z[1][4]['typeid']="top";
$z[1][4]['row']="7";

?>